# https://medium.com/@tomer.klein/docker-compose-and-mosquitto-mqtt-simplifying-broker-deployment-7aaf469c07ee
version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: smart_home_mosquitto
    restart: unless-stopped
    ports:
      - "192.168.1.100:1883:1883"
      # - "127.0.0.1:9001:9001"
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
